// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingMallBeckend.Data;

#nullable disable

namespace ParkingMallBeckend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240901054557_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParkingMallBeckend.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("ParkingMallBeckend.Models.DetailParkir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BiayaParkir")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BiayaPerJam")
                        .HasColumnType("int");

                    b.Property<int>("ParkirId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParkirId");

                    b.ToTable("detailParkirs");
                });

            modelBuilder.Entity("ParkingMallBeckend.Models.Parkir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PlateNomor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeTransportasiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WaktuMasuk")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TypeTransportasiId");

                    b.ToTable("parkirs");
                });

            modelBuilder.Entity("ParkingMallBeckend.Models.TypeTransportasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BiayaPerJam")
                        .HasColumnType("int");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("typeTransportasis");
                });

            modelBuilder.Entity("ParkingMallBeckend.Models.DetailParkir", b =>
                {
                    b.HasOne("ParkingMallBeckend.Models.Parkir", "Parkir")
                        .WithMany()
                        .HasForeignKey("ParkirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parkir");
                });

            modelBuilder.Entity("ParkingMallBeckend.Models.Parkir", b =>
                {
                    b.HasOne("ParkingMallBeckend.Models.TypeTransportasi", "TypeTransportasi")
                        .WithMany()
                        .HasForeignKey("TypeTransportasiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TypeTransportasi");
                });
#pragma warning restore 612, 618
        }
    }
}
